---
client: >-
  java -Djava.net.preferIPv4Stack=true -cp bin
  ch.usi.inf.paxos.test.Main
  client
acceptor: >-
  java -Djava.net.preferIPv4Stack=true -cp bin
  ch.usi.inf.paxos.test.Main
  acceptor
learner: >-
  java -Djava.net.preferIPv4Stack=true -cp bin
  ch.usi.inf.paxos.test.Main
  learner
proposer: >-
  java -Djava.net.preferIPv4Stack=true -cp bin
  ch.usi.inf.paxos.test.Main
  proposer

system_path: /projects/nfv-consensus/src/paxos/
